### ISSUE TITLE
Add an option to check for indirect dependencies.

### ISSUE THREAD

**Issue by GaurangTandon** [ammarbinfaisal/depson#1]
https://github.com/ammarbinfaisal/depson/blob/3213636c3a1e37062fca49a67ff22a06790523dd/bin.js#L13

Aka is the dependency checking transitive?

**Comment by ammarbinfaisal** [comment]
nope. btw this can be great feature. I dont have time to implement this rn. I'll surely do this after gci gets over unless u want to go for it :smile: .

**Comment by GaurangTandon** [comment]
Sure, have a go at it, also be careful of cyclic dependencies, i.e., A depends on B depends on C depends on D depends on E depends back on A :O

**Comment by ammarbinfaisal** [comment]
this isnt fixed. node_modules inside a  node_modules/<some package> is being read
